######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 29 20:01:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Imagearea.h mainwindow.h
SOURCES += Imagearea.cpp main.cpp mainwindow.cpp
